prgrms-fe-devcourse/FEDC3_SWithMe_Gidong

- src/api/channel.js
- src/api/core/index.js
- src/utils/storage.js
- close #7 
- 이상한 점이 있으면 말씀해주세요.
> [feat] 채널 정보 불러오는 API 연결

- src/App.jsx
- src/api/channel.js
- src/api/post.js
- src/components/domain/GroupInfoModal/index.jsx
- src/components/domain/GroupItem/index.jsx
- src/components/domain/groupInfo/Member.jsx
- src/context/GroupProvider.jsx
- src/pages/MyGroup.jsx
- close #38
- axios delete는 data안에 담아야 한다..
- 우려되는 부분
- 궁금한 점
> feat: 그룹 정보 모달 연결 및 그룹 삭제 api 연동

- src/App.jsx
- src/api/post.js
- src/components/base/Modal/index.jsx
- src/context/TILProvider.jsx
- src/pages/TILEditor.jsx
- close #48 
- 우려되는 부분
- 궁금한 점
> [feat] TIL 작성 페이지 API 연동

- src/App.jsx
- src/api/comment.js
- src/api/like.js
- src/api/post.js
- src/components/domain/CommentItem/index.jsx
- src/components/domain/TILItem/index.jsx
- src/context/CommentProvider.jsx
- src/context/LikeProvider.jsx
- src/context/TILProvider.jsx
- src/pages/TIL.jsx
- close #56
- 댓글 수정 api가 문서에 없어서 삭제 후 다시 생성하는걸로 일단 대체했습니다.
- 우려되는 부분
- 그래서 수정하면 최하단으로 간다는 점..
- 궁금한 점
> [feat] TIL 보기 페이지 api 연동

- src/components/domain/SearchResult/SearchResultContainer.jsx
- src/components/domain/SearchResult/SearchResultGroup.jsx
- src/components/domain/SearchResult/index.jsx
- src/pages/SearchResult.jsx
- close #63 
- 우려되는 부분
- 궁금한 점
> [design] 그룹 검색 페이지 스타일링

- src/App.jsx
- src/api/user.js
- src/components/domain/CreateGroupModal/index.jsx
- src/components/domain/GroupInfoModal/index.jsx
- src/components/domain/GroupItem/index.jsx
- src/components/domain/GroupList/index.jsx
- src/context/GroupProvider.jsx
- src/context/UserProvider.jsx
- src/pages/ManageGroup.jsx
- src/pages/SignUp.jsx
- close #66
- 기존 group과 description이 달라져서 기존 group은 삭제해야 합니다.
- 우려되는 부분
- description 수정하면서 제가 생각하지 못한 부분에서 에러가 날 수도 있습니다..
- 궁금한 점
> fix: 그룹 정보 모달에서 탈퇴하기로 변경, 그룹 description 수정

- src/components/domain/AlarmModal/index.jsx
- src/components/domain/Header/HeaderUserNav.jsx
- close #61 
- 우려되는 부분
- 궁금한 점
> [feat] 알림 모달 레이아웃

- .eslintrc.json
- src/App.jsx
- src/api/alarm.js
- src/components/domain/AlarmModal/index.jsx
- src/components/domain/CommentItem/index.jsx
- src/components/domain/Header/HeaderUserNav.jsx
- src/context/CommentProvider.jsx
- src/context/LikeProvider.jsx
- src/pages/TIL.jsx
> [feat] 알림 모달 api 연동

- src/components/domain/SearchResult/SearchResultGroup.jsx
- src/components/domain/TemplateHeader/SearchBar.jsx
- src/pages/SearchResult.jsx
- close #75 
- 우려되는 부분
- 궁금한 점
급하게 만들어서 그런지 아직 개선해야할 부분이 많습니당
반복되는 컴포넌트 정리,
검색 결과 함수 정리 등등...
그 외의 지적사항 대환영 🥳 
https://user-images.githubusercontent.com/73218463/213650300-5295a03e-1a84-4051-bdd9-1401de2ec3f8.mov
> [feat] 검색 결과 페이지

- src/components/domain/SearchResult/SearchResultContainer.jsx
- src/components/domain/SearchResult/SearchResultGroup.jsx
- src/components/domain/TemplateHeader/SearchBar.jsx
- src/pages/SearchResult.jsx
- src/styles/color.js
- close #80
- 우려되는 부분
- 궁금한 점
https://user-images.githubusercontent.com/73218463/213689864-86815c22-0a06-4ed8-98d9-6ee7687cd982.mov
> [design] 헤더, 검색결과 페이지 디자인 수정

- src/components/domain/AlarmModal/index.jsx
> [fix] 읽지 않은 메시지가 없을 때 처리

- src/components/domain/CreateGroupModal/index.jsx
- close #96 
- toast 추가할 예정이라 error message는 따로 분기처리 안했습니다.
> [fix] 동일 그룹 명 생성 시 에러

- package.json
- src/App.jsx
- src/components/base/Tag/index.jsx
- src/components/base/Toast/ToastItem.jsx
- src/components/base/Toast/index.jsx
- src/components/base/index.js
- src/components/domain/CommentItem/index.jsx
- src/components/domain/CreateGroupModal/index.jsx
- src/components/domain/TemplateHeader/SearchBar.jsx
- src/context/ToastProvider.jsx
- src/hooks/useTimeout.js
- src/hooks/useTimeoutFn.js
- src/pages/ManageGroup.jsx
- src/pages/MyPage.jsx
- src/pages/SignIn.jsx
- src/pages/SignUp.jsx
- yarn.lock
- close #106 
- 구현하고 보니 딱히 넣을데가 많진 않네요.. ㅋㅋ
> [feat] Toast 구현 및 alert 변경

- src/components/base/Pagination/index.jsx
- src/components/base/Text/index.jsx
- src/components/domain/SearchResult/SearchResultContainer.jsx
- src/components/domain/SearchResult/SearchResultGroup.jsx
- src/components/domain/TILList/index.jsx
- src/pages/JoinGroup.jsx
- src/pages/SearchResult.jsx
- close #100
- 중복을 줄이고자 했습니다. 수정한 코드에 대해 궁금한 점이 있으시면 말씀해주세요!! 
- 기존에 그룹이 한 페이지당 8개씩 나왔는데 너무 많은 것 같기도 해서 5개로 줄였습니다. 
- 자세히 보기 보다 좀 더 직관적인 이름으로 바꾸는 것이 좋을 것 같아 그룹 수정하기로 수정하였습니다.
> [design] 검색 결과 페이지 스타일링 수정

- src/components/base/Input/index.jsx
- src/components/base/Tag/index.jsx
- src/components/base/Textarea/index.jsx
- src/components/domain/CommentItem/index.jsx
- src/components/domain/CreateComment/index.jsx
- src/components/domain/CreateGroupModal/index.jsx
- src/pages/ManageGroup.jsx
- src/pages/MyPage.jsx
- src/pages/TILEditor.jsx
- src/stories/components/base/Textarea.stories.jsx
- close #108 
- 바꾸니까 훨씬 깔끔한 것 같ටㅏ유
디자인적으로 변경점이 없습니다.
> [feat] Input, TagInput, Textarea ref 방식에서 state 방식으로 변경

- src/components/domain/SearchResult/SearchResultContainer.jsx
> [feat] 그룹 검색 결과 없을 경우 Empty 처리 

- src/components/base/Modal/index.jsx
- src/components/base/Modal/styles.js
- src/components/base/Pagination/index.jsx
- src/components/base/Pagination/styles.js
- src/components/base/SearchBar/index.jsx
- src/components/base/SearchBar/styles.js
- src/components/base/Spinner/index.jsx
- src/components/base/Spinner/styles.js
- src/components/base/Tag/TagInput.jsx
- src/components/base/Tag/TagItem.jsx
- src/components/base/Tag/index.jsx
- src/components/base/Tag/styles.js
- src/components/base/Textarea/index.jsx
- src/components/base/Textarea/styles.js
- src/components/base/Toast/ToastItem.jsx
- src/components/base/Toast/index.jsx
- src/components/base/Toast/styles.js
- src/components/base/index.js
- src/styles/color.js
- close #119 
- 우려되는 부분
하단 코멘트로 남겨놓았습니다
> [refactor] style 코드 분리 작업 (Base, J-Z)

- src/components/template/index.jsx
- src/components/template/styles.js
- close #129 
- 우려되는 부분
- 궁금한 점
x
x
> [refactor] Template 컴포넌트 스타일 코드 분리

- .eslintrc.json
- src/api/core/index.js
> [refactor] axios 인스턴스 코드 리팩토링

- src/styles/theme.js
- close #133 
- 우려되는 부분
- 궁금한 점
x
다음과 같이 적용할 때
theme을 import 하고 다음과 같이 작성하면 됩니당.
> [feat] custom theme 코드 작성

- src/App.jsx
- src/components/base/Avatar/index.jsx
- src/components/base/Avatar/styles.js
- src/components/base/Badge/index.jsx
- src/components/base/Badge/styles.js
- src/components/base/Button/index.jsx
- src/components/base/Button/styles.js
- src/components/base/Calendar/index.jsx
- src/components/base/Calendar/styles.js
- src/components/base/Divider/index.jsx
- src/components/base/Divider/styles.js
- src/components/base/Empty/index.jsx
- src/components/base/Empty/styles.js
- src/components/base/Heading/index.jsx
- src/components/base/Icon/index.jsx
- src/components/base/Icon/styles.js
- src/styles/theme.js
- close #137 
base 컴포넌트, style 관련 코드들을 리팩터링 합니다 - 1
(Avatar ~ Image)
궁금한 부분, 밑에 코멘트로 남겨두었습니다
> [refactor] base 컴포넌트 style 코드 리팩터링 - 1

- src/components/base/Modal/index.jsx
- src/components/base/Modal/styles.js
- src/components/base/Pagination/index.jsx
- src/components/base/Pagination/styles.js
- src/components/base/Spinner/index.jsx
- src/components/base/Spinner/styles.js
- src/components/base/Tag/TagInput.jsx
- src/components/base/Tag/TagItem.jsx
- src/components/base/Tag/index.jsx
- src/components/base/Tag/styles.js
- src/components/base/Text/index.jsx
- src/components/base/Textarea/index.jsx
- src/components/base/Textarea/styles.js
- src/components/base/Toast/ToastItem.jsx
- src/components/base/Toast/index.jsx
- src/components/base/Toast/styles.js
- close #142 
- 우려되는 부분
- 궁금한 점
- 이후에 TODO
그룹 생성시에 Input의 propTypes중 size에 medium이 없어 계속 warning이 뜨고있습니다
이전에 base/divider 컴포넌트수정할때 제가 이상한걸 건드렸나 봅니다. 같이 수정해볼게요
x
> [refactor] base 컴포넌트 style 코드 리팩터링 - 2

- src/components/domain/TemplateHeader/SearchBar.jsx
- close #155 
기능에 대한 부분은 아니지만 참고해야할 부분
01.
localhost를 오랫동안 띄워놨더니 수시로 알림 GET요청이가서 제 ip가 서버로부터 타임아웃 먹은것 같아요
여러분을은 작업하실때 hook/queries/notifications.js에 refetchInterval옵션 빼놓고 작업하시길 바랍니다
02.
ReactQuery 도입이전 알림 요청값들에 인해 에러가 계속 납니다, DB한번 밀어야할것같아요.
DB밀기전까지는 새로운 아이디를 생성해서 작업하시는걸 권장합니다.
> [feat] 검색 후 검색값을 input창에 남겨놓기

- src/components/base/Avatar/index.jsx
- src/components/base/Button/index.jsx
- src/components/base/Input/index.jsx
- src/components/base/Tag/TagInput.jsx
- src/components/base/Tag/TagItem.jsx
- src/components/base/Tag/styles.js
- src/components/domain/GroupItem/index.jsx
- src/components/domain/GroupItem/styles.js
> [refactor] 일부 base component 수정

- src/components/domain/AlarmModal/styles.js
- src/components/domain/HamburgerModal/index.jsx
- src/components/domain/HamburgerModal/styles.js
- src/components/domain/TemplateHeader/Logo.jsx
- src/components/domain/TemplateHeader/UserNav/Authorized.jsx
- src/components/domain/TemplateHeader/styles.js
- src/components/template/index.jsx
- src/components/template/styles.js
- src/stores/searchBar.js
- src/styles/keyframes.js
- close #153 
- x
https://user-images.githubusercontent.com/34560965/231448991-4847d658-93e4-4d18-80ca-b3921a2411dc.mov
> [feat] 헤더 반응형 추가

- src/components/domain/SearchResult/SearchResultContainer.jsx
- src/components/domain/SearchResult/SearchResultGroup.jsx
- src/components/domain/SearchResult/styles.js
- src/pages/SearchResult.jsx
- close #166 
x
https://user-images.githubusercontent.com/73218463/232674886-612513e3-04aa-4232-9111-6f31991de7a3.mov
> [feat] 검색 결과 페이지 반응형

- src/components/template/styles.js
- src/pages/MyPage.jsx
- close #162 
- x
https://user-images.githubusercontent.com/34560965/232492134-c374c74e-ed67-424d-895c-4dc06f5cf3e3.mov
> [feat] 내 정보 페이지 반응형

- src/pages/SearchResult.jsx
- src/utils/regex.js
- close #156 
- 우려되는 부분
- 궁금한 점
> [feat] 띄어쓰기 상관없이 검색 되도록 기능 추가

- src/Router.jsx
- src/pages/NotFound.jsx
- close #89 
조금 더 자연스러운 문구나 디자인 구조가 있다면 말해주세요
https://github.com/prgrms-fe-devcourse/FEDC3_SWithMe_Gidong/assets/73218463/a3c32aef-802e-4147-8978-20e45d44efed
> [feat] 404페이지 작성

- src/pages/JoinGroup.jsx
- close #168 
- x
https://user-images.githubusercontent.com/34560965/233789368-cc4713d1-5553-46b3-aed5-3f4cea22185e.mov
> [feat] 그룹 가입 페이지 반응형
